### ISSUE TITLE
Do you have uncompressed files about pdf.viewer.js?

### ISSUE THREAD

**Issue by shunchuan** [yshurik/qpdfjs#4]
Hello
   Now I am going to run the program in embedded, so I need to make some changes to the code,do  you have uncompressed files about pdf.viewer.js? Or tell me where can I find it? 
  Thank you for your time and I look forward to your reply.

**Comment by yshurik** [comment]
Those were just picked from pdf.js project as far as I remember.

**Comment by yshurik** [comment]
Ref https://medium.com/@ProgRockRec/power-of-qt-making-a-pdf-viewer-desktop-application-in-a-few-hours-14cfc3a1c9ae

**Comment by shunchuan** [comment]
I had clone the pdf.js project before,but i did not found any codes about qwebchannel, so i doubt is was not built from that project.
After reading the blog you provided, I understand that you have added these yourself, but I don't know how to add it, is ./web/viewer.js ? or ./examples/?/viewer.js?
I think I should study pdf.js carefully.

**Comment by yshurik** [comment]
I guess you need to look at [pdf.js.diff](https://github.com/yshurik/qpdfjs/blob/master/pdf.js.diff) (in the root). It has changes which where applied to pdf.js

**Comment by shunchuan** [comment]
I'm sorry for not responding for so long.
I have completed the changes on the project with your help , but I regret that this solution was terminated in my project , because it could not run efficiently on the embedded.
Mupdf and poppler are currently selected.
Thank you again!
